libs/filebrowser/urls.py
# As of version 3.4, all urls moved to FileBrowserSite class in filebrowser.sites

libs/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.conf import settings


urlpatterns = patterns('',
    
    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', 'grappelli.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^lookup/m2m/$', 'grappelli.views.related.m2m_lookup', name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', 'grappelli.views.related.autocomplete_lookup', name="grp_autocomplete_lookup"),

    # GRAPPELLI DOM DOCUMENTATION
    url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),
    
    url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),
    
    url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),
    
    url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),
    
    url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),
    
    url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),
    
    url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),
    
    url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),
    
    url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),
    
    url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

#views
from django.views.generic import TemplateView

from views import Home

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# filebrowser
from filebrowser.sites import site

# statics
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', Home.as_view(), {}, "home_view"),
    
    url(r'^dossier/', include('dossiers.urls')),
    url(r'^infos/', include('articles.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^medias/', include('medias.urls')),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG: 
    urlpatterns += patterns('',
                            url(r'^medias/(?P<path>.*)/?$' , 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, }),
                            (r'^404$', TemplateView.as_view(template_name="404.html")),
                            (r'^500$', TemplateView.as_view(template_name="500.html")),
                            )

libs/filebrowser/models.py
# This file is only necessary for the tests to work

libs/filebrowser/forms.py
# coding: utf-8

# PYTHON IMPORTS
import re, os

# DJANGO IMPORTS
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext as _

# FILEBROWSER IMPORTS
from filebrowser.settings import MAX_UPLOAD_SIZE, FOLDER_REGEX
from filebrowser.functions import convert_filename

alnum_name_re = re.compile(FOLDER_REGEX, re.U)


# CHOICES
TRANSPOSE_CHOICES = (
    ("", u"-----"),
    ("0", _(u"Flip horizontal")),
    ("1", _(u"Flip vertical")),
    ("2", _(u"Rotate 90° CW")),
    ("4", _(u"Rotate 90° CCW")),
    ("3", _(u"Rotate 180°")),
)


class CreateDirForm(forms.Form):
    """
    Form for creating a folder.
    """
    
    def __init__(self, path, *args, **kwargs):
        self.path = path
        self.site = kwargs.pop("filebrowser_site", None)
        super(CreateDirForm, self).__init__(*args, **kwargs)
        
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['name'])


class ChangeForm(forms.Form):
    """
    Form for renaming a file/folder.
    """
    
    custom_action = forms.ChoiceField(label=_(u'Actions'), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.fileobject = kwargs.pop("fileobject", None)
        from filebrowser.sites import site
        self.site = kwargs.pop("filebrowser_site", None)
        super(ChangeForm, self).__init__(*args, **kwargs)
        
        # Initialize choices of custom actions 
        choices = [("",u"-----"),]
        
        for name, action in self.site.applicable_actions(self.fileobject):
            choices.append((name, action.short_description))
        
        self.fields['custom_action'].choices=choices

    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif self.site.storage.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name'])))  and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

libs/filebrowser/views.py
# As of version 3.4, all views moved to FileBrowserSite class in filebrowser.sites

libs/filebrowser/templates/filebrowser/createdir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n fb_tags fb_csrf %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="grp-content-container">
    <form action="{% query_string '' 'p' %}" method="post">{% fb_csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="grp-module aligned">
            <div class="grp-row {% if form.dir_name.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_dir_name">{{ form.name.label }}</label></div>
                    <div class="c-2">
                        {{ form.name }}
                        {% if form.dir_name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                        <p class="grp-help">
                            {{ form.name.help_text|safe }}
                            {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                                <br />
                                {% if settings_var.NORMALIZE_FILENAME %}
                                    {% trans "The Name will be normalized by converting or stripping all non-standard characters." %} <br />
                                {% endif %}
                                {% if settings_var.CONVERT_FILENAME %}
                                    {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li><input type="submit" value="{% trans 'Submit' %}" class="grp-button grp-default" /></li>
            </ul>
        </div>
    </form>
</div>
{% endblock %}

libs/filebrowser/templates/filebrowser/custom_field.html
{% load i18n fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value.path }}" /><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>
{% if value.filetype == "Image" %}
{% version_object value.path final_attrs.ADMIN_THUMBNAIL as thumbnail_version %}
{% if thumbnail_version %}
<p class="preview" id="preview_{{ final_attrs.id }}">
    <a href="{{ value.url }}" target="_blank" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" src="{{ thumbnail_version.url }}" class="preview" />
    </a>
</p>
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% if value and not value.exists %}
<ul class="errorlist"><li>{% trans "File not found" %}</li></ul>
{% endif %}

libs/filebrowser/templates/filebrowser/delete_confirm.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n fb_tags fb_versions %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-delete-confirmation grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
    <div class="g-d-c">
        <div class="grp-group">
            <h2>{% blocktrans with fileobject.filename as escaped_object %}Are you sure you want to delete "{{ escaped_object }}"? All of the following items will be deleted:{% endblocktrans %}</h2>
            <ul class="grp-nested-list">
                <li>{{ fileobject.filename }}</li>
            </ul>
            {% if filelisting %}
                <ul class="grp-nested-list">
                    {% for item in filelisting %}
                        <li>{{ item.path_relative_directory }}</li>
                    {% endfor %}
                <ul>
            {% endif %}
            {% if additional_files %}
                <ul class="grp-nested-list">
                    <li>{% blocktrans with additional_files as escaped_object %}... and {{ escaped_object }} more Files.{% endblocktrans %}</li>
                </ul>
            {% endif %}
        </div>
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul {% if is_popup %}style="overflow: auto;"{% endif %}>
                <li class="grp-float-left"><a href="{% url filebrowser:fb_detail %}{% query_string %}" class="grp-button grp-cancel-link">{% trans "Cancel" %}</a></li>
                <li><a href="{% url filebrowser:fb_delete %}{% query_string %}" class="grp-button">{% trans "Yes, I'm sure" %}</a></li>
            </ul>
        </footer>
    </div>
{% endblock %}

libs/filebrowser/templates/filebrowser/detail.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n fb_tags fb_versions %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
    (function($){
        $(document).ready(function() {
            $("div#grp-content-container .grp-collapse").grp_collapsible({
                on_init: function(elem, options) {
                    // open collapse (and all collapse parents) in case of errors
                    if (elem.find("ul.grp-errorlist").length > 0) {
                        elem.removeClass("grp-closed")
                            .addClass("grp-open");
                        elem.parents(".grp-collapse")
                            .removeClass("grp-closed")
                            .addClass("grp-open");
                    }
                }
            });
        });
    })(grp.jQuery);
    </script>
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-change-form grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="grp-content-container">
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="grp-module">
            <div class="grp-row {% if form.name.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_name">{{ form.name.label }}</label></div>
                    <div class="c-2">
                        {{ form.name }}
                        {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                        {% if form.name.help_text %}<p class="grp-help">{{ form.name.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </fieldset>
        {% if fileobject.filetype == "Image" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "Edit" %}</h2>
            <div class="grp-row {% if form.custom_action.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_custom_action">{{ form.custom_action.label }}</label></div>
                    <div class="c-2">
                        {{ form.custom_action }}
                        {% if form.custom_action.errors %}<ul class="errorlist">{{ form.custom_action.errors }}</ul>{% endif %}
                        {% if form.custom_action.help_text %}<p class="help">{{ form.custom_action.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "Folder Information" %}</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Date" %}</label></div>
                    <div class="c-2">
                        <p class="grp-readonly">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype != "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "File Information" %}</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "URL" %}</label></div>
                    <div class="c-2">
                        <p class="grp-readonly">
                            <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Filesize" %}</label></div>
                    <div class="c-2">
                        <p class="grp-readonly">
                            {{ fileobject.filesize|filesizeformat }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Date" %}</label></div>
                    <div class="c-2">
                        <p class="grp-readonly">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
            {% if fileobject.filetype == "Image" %}
                <div class="grp-row">
                    <div class="l-2c-fluid l-d-4">
                        <div class="c-1"><label>{% trans "Size" %}</label></div>
                        <div class="c-2">
                            <p class="grp-readonly">
                                {{ fileobject.width }} x {{ fileobject.height }} px
                            </p>
                        </div>
                    </div>
                </div>
            {% endif %}
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Image" %}
        <fieldset class="grp-module grp-collapse grp-closed">
            <h2 class="grp-collapse-handler">{% trans "Image Versions" %}</h2>
            {% if settings_var.ADMIN_THUMBNAIL %}
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Thumbnail" %}</label></div>
                    <div class="c-2">
                        <img src="{% version fileobject.path settings_var.ADMIN_THUMBNAIL %}" title="{% trans 'View Image' %}" />
                    </div>
                </div>
            </div>
            {% endif %}
            {% if settings_var.ADMIN_VERSIONS %}
                {% for version in settings_var.ADMIN_VERSIONS %}
                    {% version_object fileobject version as image_version %}
                    {% version_setting version %}
                    <div class="grp-row">
                        <div class="l-2c-fluid l-d-4">
                            <div class="c-1"><label>{{ version_setting.verbose_name }}</label></div>
                            <div class="c-2">
                                <img src="{{ image_version.url }}" />
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </fieldset>
        {% endif %}
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li class="grp-float-left"><a href="{% url filebrowser:fb_delete_confirm %}{% query_string %}" class="grp-button grp-delete-link">{% trans "Delete" %}</a></li>
                <li><input type="submit" value="{% trans 'Save' %}" class="grp-button grp-default" /></li>
                <li><input type="submit" value="{% trans 'Save and continue editing' %}" class="grp-button" name="_continue" /></li>
            </ul>
        </footer>
    </form>
</div>
{% endblock %}

libs/filebrowser/templates/filebrowser/version.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n fb_tags fb_versions %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    {% ifequal query.pop '1' %} <!-- FileBrowseField -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_FileBrowseField.js"></script>
    {% endifequal %}
    {% ifequal query.pop '2' %} <!-- TinyMCE -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_TINYMCE }}tiny_mce_popup.js"></script>
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_TinyMCE.js"></script>
    {% if query.mce_rdomain %}<script language="javascript">document.domain = "{{ query.mce_rdomain }}"</script>{% endif %}
    {% endifequal %}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-change-list grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% endblock %}

<!-- OBJECT-TOOLS -->
{% block object-tools %}{{ image_version.path }}{% endblock %}

<!-- CONTENT -->
{% block content %}
    {% if fileobject.filetype == "Image" %}
        {% version_object fileobject.path settings_var.ADMIN_THUMBNAIL as thumbnail_version %}
        {% version_object fileobject.path query.version as image_version %}
        {% ifequal query.pop '1' %} <!-- FileBrowseField -->
        <script type="text/javascript" charset="utf-8">
            (function($) {
                $(document).ready(function() {
                    FileSubmit('{{ image_version.path }}', '{{ image_version.url }}', '{{ thumbnail_version.url }}', '{{ image_version.filetype }}');
                });
            })(grp.jQuery);
        </script>
        {% endifequal %}
        {% ifequal query.pop '2' %} <!-- TinyMCE -->
        <script type="text/javascript" charset="utf-8">
            (function($) {
                $(document).ready(function() {
                    FileBrowserDialogue.fileSubmit('{{ image_version.url|escapejs }}');
                });
            })(grp.jQuery);
        </script>
        {% endifequal %}
    {% endif %}
{% endblock %}